# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9afb44c431c69fbebb58d69464d6c6d584d73bc9ed6b6e68ec0f7e870babad4378df9c408d678494161b78c26202a5b0492672b469df23e947217f24e51385a

test:
  secret_key_base: d5ac1fe1a73c6da4385e2235db7f6381b19f009ce26b2479a28dfa690d4d1b872b73aeec5603327e0710f4dcfdb26fe3c1787017dcf8a9a03230d9dc9307c119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
